sudo: false
dist: trusty
language: perl
python: 2.7.10
perl:
- '5.26'
- '5.14'
addons:
  apt:
    packages:
    - libdb-dev
    - libgd2-noxpm-dev
  firefox: '58.0'
cache:
  directories:
  - extlib/
  - "$HOME/perl5/"
  - node_modules/
  - "$HOME/python/"
  - "$HOME/.nvm/"
  - "$HOME/geckodriver"
install:
- |
  if [[ ! -f ~/geckodriver/geckodriver ]]; then
    rm -rf ~/geckodriver;
    mkdir ~/geckodriver;
    wget -O - https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-linux64.tar.gz | tar -xzf - -C ~/geckodriver;
  fi
- export PATH=$PATH:$HOME/geckodriver
- cpanm --notest GD::Image Text::Markdown DateTime JSON
- npm install -g jshint
# only init the python virtualenv if it did not show up in our build cache
- if [[ ! -f ~/python/bin/activate ]]; then virtualenv ~/python; fi
- source ~/python/bin/activate
- pip install nose selenium
script:
- jshint src/JBrowse/
- if [[ "x$TRAVIS_TAG" != "x" ]]; then build/set_package_versions.pl $TRAVIS_TAG src/JBrowse/package.json package.json; fi
- RELEASE_VERSION=`node -e 'require("fs").readFile("src/JBrowse/package.json", (e,d)=>console.log(JSON.parse(d).version))'`
- BUILD_DIR=$PWD
# if we are building for inclusion into the `dev` branch, run the minification and test against that
- |
  if [[ "x$TRAVIS_TAG" != "x" || $TRAVIS_BRANCH = "master" || $TRAVIS_BRANCH = "dev" || $TRAVIS_PULL_REQUEST != "false" ]]; then
    make -f build/Makefile release;
    rm -rf JBrowse-*/;
    unzip -q JBrowse-$RELEASE_VERSION.zip;
    cp -r tests/ JBrowse-$RELEASE_VERSION/;
    cd JBrowse-$RELEASE_VERSION/;
  fi
- ./setup.sh legacy;
- prove -Isrc/perl5 -r -j3 tests/perl_tests;
- utils/jb_run.js -p 9000 &
- MOZ_HEADLESS=1 SELENIUM_BROWSER=firefox JBROWSE_URL=http://localhost:9000/index.html tests/selenium_tests/travis_wrapper.sh;
- cd $BUILD_DIR
after_failure:
- cat JBrowse-*/setup.log
- find JBrowse-*/extlib/lib/perl5
- cat JBrowse-*/src/build-report.txt
deploy:
# upload both minified and non-minified builds to GitHub releases
- provider: releases
  api_key:
    secure: BuOD7rqrcGKT3g0hVY5AGpJI/Kkko4DhSIYSUQ28sS2AOdoNyTD0t5doL/Kiq4BC41q198tbFFt1dnXGdo8YKpBSXO/uGUuuiGtMFHM++I84oLq20p49iyrenNZ4m/jy/Q4YtizIYLs83DVzVdQzhJ5hrTx6f+d1gc9EgaMeBF4=
  file: JBrowse-1.*.zip
  file_glob: true
  skip_cleanup: true
  on:
    repo: GMOD/jbrowse
    perl: 5.26
    tags: true
# upload regular non-minified version to npm
- provider: npm
  email: rbuels@gmail.com
  skip_cleanup: true
  api_key:
    secure: mgvlVdeMAR35C69+NERuYK4YGwbBAQsnSXS7IJhn3CRNgbtWh2zqaVV8NbHWitD9RJmocTbkIe94MfD8HfI3zBAgIVewckQ0QWMyjAJuWJR2Zw91R309aIQpbsix4kNCP9RDDrtfzovptBJ6JS8UwEk5CsQ7Wfohctek59+UnyU=
  on:
    repo: GMOD/jbrowse
    perl: 5.26
    tags: true
